export const allActivities = {
  "jan-27": [
    {
      id: 1,
      name: "Senso-ji Temple & Nakamise Shopping Street Senso-ji",
      timing: "8:15 am Morning",
      duration: "3 hours",
      pickUp: "From Hotel",
      background: "/activities/1.jpg",
    },
    {
      id: 2,
      name: "Mount Fuji Day Trip & Lake Kawaguchi",
      timing: "7:30 am Morning",
      duration: "8 hours",
      pickUp: "From Hotel",
      background: "/activities/2.jpg",
    },
    {
      id: 3,
      name: "Tokyo Skytree & Sumida River Cruise",
      timing: "2:00 pm Afternoon",
      duration: "4 hours",
      pickUp: "Meeting Point",
      background: "/activities/3.jpg",
    },
  ],
  "jan-28": [
    {
      id: 4,
      name: "Tsukiji Fish Market Tour & Sushi Making Class",
      timing: "9:00 am Morning",
      duration: "5 hours",
      pickUp: "Meeting Point",
      background: "/activities/1.jpg",
    },
    {
      id: 5,
      name: "Akihabara Electric Town & Anime Tour",
      timing: "1:00 pm Afternoon",
      duration: "3 hours",
      pickUp: "From Hotel",
      background: "/activities/3.jpg",
    },
  ],
  "jan-29": [
    {
      id: 6,
      name: "Hakone Hot Springs & Mt. Fuji View Day Trip",
      timing: "7:00 am Morning",
      duration: "10 hours",
      pickUp: "From Hotel",
      background: "/activities/2.jpg",
    },
  ],
  "jan-30": [
    {
      id: 7,
      name: "Shinjuku Gyoen National Garden Tour",
      timing: "10:30 am Morning",
      duration: "2 hours",
      pickUp: "Meeting Point",
      background: "/activities/1.jpg",
    },
    {
      id: 8,
      name: "Tokyo Metropolitan Government Building Observatory",
      timing: "4:00 pm Afternoon",
      duration: "1 hour",
      pickUp: "Self-guided",
      background: "/activities/3.jpg",
    },
    {
      id: 9,
      name: "Robot Restaurant Show & Dinner",
      timing: "7:30 pm Evening",
      duration: "3 hours",
      pickUp: "From Hotel",
      background: "/activities/2.jpg",
    },
  ],
  "jan-31": [
    {
      id: 10,
      name: "Meiji Shrine & Yoyogi Park Walking Tour",
      timing: "9:00 am Morning",
      duration: "3 hours",
      pickUp: "From Hotel",
      background: "/activities/2.jpg",
    },
    {
      id: 11,
      name: "Harajuku Fashion Street & Takeshita Street Tour",
      timing: "2:00 pm Afternoon",
      duration: "2 hours",
      pickUp: "Meeting Point",
      background: "/activities/1.jpg",
    },
  ],
  "feb-1": [
    {
      id: 12,
      name: "Nikko National Park & Toshogu Shrine Day Trip",
      timing: "7:15 am Morning",
      duration: "11 hours",
      pickUp: "From Hotel",
      background: "/activities/3.jpg",
    },
  ],
  "feb-2": [
    {
      id: 13,
      name: "Kamakura Great Buddha & Hokokuji Temple Tour",
      timing: "8:30 am Morning",
      duration: "7 hours",
      pickUp: "From Hotel",
      background: "/activities/1.jpg",
    },
    {
      id: 14,
      name: "Enoshima Island Seaside Tour",
      timing: "3:30 pm Afternoon",
      duration: "4 hours",
      pickUp: "Meeting Point",
      background: "/activities/2.jpg",
    },
  ],
  "feb-3": [
    {
      id: 15,
      name: "Odaiba Entertainment District & TeamLab Borderless",
      timing: "10:00 am Morning",
      duration: "6 hours",
      pickUp: "Self-guided",
      background: "/activities/3.jpg",
    },
    {
      id: 16,
      name: "Tokyo Bay Sunset Cruise",
      timing: "5:30 pm Evening",
      duration: "2 hours",
      pickUp: "Meeting Point",
      background: "/activities/1.jpg",
    },
  ],
  "feb-4": [
    {
      id: 17,
      name: "Ueno Park & Museums Tour",
      timing: "9:30 am Morning",
      duration: "5 hours",
      pickUp: "From Hotel",
      background: "/activities/2.jpg",
    },
  ],
  "feb-5": [
    {
      id: 18,
      name: "Shibuya Crossing & Shopping District Tour",
      timing: "11:00 am Morning",
      duration: "3 hours",
      pickUp: "Meeting Point",
      background: "/activities/3.jpg",
    },
    {
      id: 19,
      name: "Tokyo Tower Night View & Dinner",
      timing: "6:00 pm Evening",
      duration: "4 hours",
      pickUp: "From Hotel",
      background: "/activities/1.jpg",
    },
  ],
};
